services:
  minio:
    container_name: minio_storage
    restart: always
    image: minio/minio:latest
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - ./minio_storage:/data
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=vercel
      - MINIO_ROOT_PASSWORD=vercel123
      - MINIO_SERVER_URL=http://192.168.29.40:9000
